services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    command: sh ./entrypoint.sh
    volumes:
      - .:/code
      - pycache:/var/cache/pycache
    ports:
      - "${APP_PORT-8000}:8000"
    environment:
      - PYTHONPYCACHEPREFIX=/var/cache/pycache
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2309
      POSTGRES_DB: fastapi
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis

volumes:
  db_data: null
  pycache: null
